// Canonical Spotify genre seeds. Backend uses these for matching.
export const MUSIC_GENRES = [
  'Latin',
  'Flamenco',
  'Bolero',
  'Reggaeton',
  'Indie Rock',
  'Singer-Songwriter',
  'Pop',
  'Rock en Español',
  'Jazz',
  'Classical',
  'Electronic',
  'Folk',
]

const LABELS = {
  English: {
    Latin: 'Latin',
    Flamenco: 'Flamenco',
    Bolero: 'Bolero',
    Reggaeton: 'Reggaeton',
    'Indie Rock': 'Indie Rock',
    'Singer-Songwriter': 'Singer-Songwriter',
    Pop: 'Pop',
    'Rock en Español': 'Rock en Español',
    Jazz: 'Jazz',
    Classical: 'Classical',
    Electronic: 'Electronic',
    Folk: 'Folk',
  },
  Spanish: {
    Latin: 'Música Latina',
    Flamenco: 'Flamenco',
    Bolero: 'Bolero',
    Reggaeton: 'Reggaetón',
    'Indie Rock': 'Indie Rock',
    'Singer-Songwriter': 'Cantautores',
    Pop: 'Pop',
    'Rock en Español': 'Rock en Español',
    Jazz: 'Jazz',
    Classical: 'Clásica',
    Electronic: 'Electrónica',
    Folk: 'Folk',
  },
  French: {
    Latin: 'Musique Latine',
    Flamenco: 'Flamenco',
    Bolero: 'Boléro',
    Reggaeton: 'Reggaeton',
    'Indie Rock': 'Indie Rock',
    'Singer-Songwriter': 'Auteur-Compositeur',
    Pop: 'Pop',
    'Rock en Español': 'Rock Espagnol',
    Jazz: 'Jazz',
    Classical: 'Classique',
    Electronic: 'Électronique',
    Folk: 'Folk',
  },
  Italian: {
    Latin: 'Musica Latina',
    Flamenco: 'Flamenco',
    Bolero: 'Bolero',
    Reggaeton: 'Reggaeton',
    'Indie Rock': 'Indie Rock',
    'Singer-Songwriter': 'Cantautori',
    Pop: 'Pop',
    'Rock en Español': 'Rock Spagnolo',
    Jazz: 'Jazz',
    Classical: 'Classica',
    Electronic: 'Elettronica',
    Folk: 'Folk',
  },
  German: {
    Latin: 'Lateinamerikanisch',
    Flamenco: 'Flamenco',
    Bolero: 'Bolero',
    Reggaeton: 'Reggaeton',
    'Indie Rock': 'Indie-Rock',
    'Singer-Songwriter': 'Singer-Songwriter',
    Pop: 'Pop',
    'Rock en Español': 'Spanischer Rock',
    Jazz: 'Jazz',
    Classical: 'Klassik',
    Electronic: 'Elektronisch',
    Folk: 'Folk',
  },
  Portuguese: {
    Latin: 'Música Latina',
    Flamenco: 'Flamenco',
    Bolero: 'Bolero',
    Reggaeton: 'Reggaeton',
    'Indie Rock': 'Indie Rock',
    'Singer-Songwriter': 'Cantautores',
    Pop: 'Pop',
    'Rock en Español': 'Rock em Espanhol',
    Jazz: 'Jazz',
    Classical: 'Clássica',
    Electronic: 'Eletrônica',
    Folk: 'Folk',
  },
}

export const localizeGenre = (genre, nativeLanguage = 'English') => {
  const map = LABELS[nativeLanguage] || LABELS.English
  return map[genre] || genre
}
