// Canonical category keys (used for backend RSS-metadata matching)
// and per-native-language display labels.

export const PODCAST_CATEGORIES = [
  'History',
  'Literature',
  'News & Politics',
  'Sports',
  'Religion',
  'Culture',
  'Comedy',
  'Interview',
  'Business',
  'Science',
  'Philosophy',
  'True Crime',
]

const LABELS = {
  English: {
    History: 'History',
    Literature: 'Literature',
    'News & Politics': 'News & Politics',
    Sports: 'Sports',
    Religion: 'Religion',
    Culture: 'Culture',
    Comedy: 'Comedy',
    Interview: 'Interview',
    Business: 'Business',
    Science: 'Science',
    Philosophy: 'Philosophy',
    'True Crime': 'True Crime',
  },
  Spanish: {
    History: 'Historia',
    Literature: 'Literatura',
    'News & Politics': 'Noticias y Política',
    Sports: 'Deportes',
    Religion: 'Religión',
    Culture: 'Cultura',
    Comedy: 'Comedia',
    Interview: 'Entrevista',
    Business: 'Negocios',
    Science: 'Ciencia',
    Philosophy: 'Filosofía',
    'True Crime': 'Crímenes Reales',
  },
  French: {
    History: 'Histoire',
    Literature: 'Littérature',
    'News & Politics': 'Actualités & Politique',
    Sports: 'Sport',
    Religion: 'Religion',
    Culture: 'Culture',
    Comedy: 'Humour',
    Interview: 'Entretien',
    Business: 'Affaires',
    Science: 'Sciences',
    Philosophy: 'Philosophie',
    'True Crime': 'Crime',
  },
  Italian: {
    History: 'Storia',
    Literature: 'Letteratura',
    'News & Politics': 'Notizie e Politica',
    Sports: 'Sport',
    Religion: 'Religione',
    Culture: 'Cultura',
    Comedy: 'Comicità',
    Interview: 'Intervista',
    Business: 'Affari',
    Science: 'Scienza',
    Philosophy: 'Filosofia',
    'True Crime': 'Cronaca Nera',
  },
  German: {
    History: 'Geschichte',
    Literature: 'Literatur',
    'News & Politics': 'Nachrichten & Politik',
    Sports: 'Sport',
    Religion: 'Religion',
    Culture: 'Kultur',
    Comedy: 'Comedy',
    Interview: 'Interview',
    Business: 'Wirtschaft',
    Science: 'Wissenschaft',
    Philosophy: 'Philosophie',
    'True Crime': 'True Crime',
  },
  Portuguese: {
    History: 'História',
    Literature: 'Literatura',
    'News & Politics': 'Notícias e Política',
    Sports: 'Esportes',
    Religion: 'Religião',
    Culture: 'Cultura',
    Comedy: 'Comédia',
    Interview: 'Entrevista',
    Business: 'Negócios',
    Science: 'Ciência',
    Philosophy: 'Filosofia',
    'True Crime': 'Crime Real',
  },
}

export const localizeCategory = (category, nativeLanguage = 'English') => {
  const map = LABELS[nativeLanguage] || LABELS.English
  return map[category] || category
}
