// Short story authors by genre — used to drive story concept generation
export const SHORT_STORY_AUTHORS = {
  romance: [
    'Nora Roberts',
    'Julia Quinn',
    'Beverly Jenkins',
    'Judith McNaught',
    'Lisa Kleypas',
  ],
  thriller: [
    'Patricia Highsmith',
    'Roald Dahl',
    'Cornell Woolrich',
    'Daphne du Maurier',
    'Patricia Cornwell',
  ],
  scifi: [
    'Ray Bradbury',
    'Isaac Asimov',
    'Philip K. Dick',
    'Ursula K. Le Guin',
    'Ted Chiang',
    'Arthur C. Clarke',
    'Harlan Ellison',
    'Octavia Butler',
  ],
  mystery: [
    'Edgar Allan Poe',
    'Arthur Conan Doyle',
    'Agatha Christie',
    'G.K. Chesterton',
    'Raymond Chandler',
    'Georges Simenon',
  ],
  adventure: [
    'Jack London',
    'Rudyard Kipling',
    'Joseph Conrad',
    'Robert Louis Stevenson',
    'Alexandre Dumas',
  ],
  comedy: [
    'P.G. Wodehouse',
    'Mark Twain',
    'O. Henry',
    'Saki',
    'Dorothy Parker',
  ],
  horror: [
    'Edgar Allan Poe',
    'H.P. Lovecraft',
    'Shirley Jackson',
    'M.R. James',
    'Stephen King',
  ],
  fantasy: [
    'Jorge Luis Borges',
    'Ursula K. Le Guin',
    'Neil Gaiman',
    'Robert E. Howard',
    'Lord Dunsany',
    'J.R.R. Tolkien',
  ],
  literary: [
    'Anton Chekhov',
    'Jorge Luis Borges',
    'James Joyce',
    'Flannery O\'Connor',
    'Franz Kafka',
    'Ernest Hemingway',
    'Gabriel García Márquez',
    'Raymond Carver',
    'Julio Cortázar',
    'Alice Munro',
  ],
  historical: [
    'Isaac Bashevis Singer',
    'Isak Dinesen',
    'Arturo Pérez-Reverte',
    'Hilary Mantel',
    'Umberto Eco',
  ],
}

// Genre metadata for UI display
export const GENRES = [
  { id: 'romance', label: 'Romance' },
  { id: 'thriller', label: 'Thriller' },
  { id: 'scifi', label: 'Science Fiction' },
  { id: 'mystery', label: 'Mystery' },
  { id: 'adventure', label: 'Adventure' },
  { id: 'comedy', label: 'Comedy' },
  { id: 'horror', label: 'Horror' },
  { id: 'fantasy', label: 'Fantasy' },
  { id: 'literary', label: 'Literary' },
  { id: 'historical', label: 'Historical Fiction' },
]
